AWSTemplateFormatVersion: 2010-09-09
Description: >-
  GraphQL API Template
Transform:
  - AWS::Serverless-2016-10-31
Globals:
  Function:
    Timeout: 5
    Runtime: nodejs14.x
    Handler: index.handler
    Tracing: Active

Parameters:
  projectName:
    Type: String
    Description: Provide the name of the project. #must be all lowercase
  RDSUsername:
    AllowedPattern: ^[a-zA-Z][a-zA-Z0-9]*$
    Type: String
    Description: The username to be used in the RDS connection.
    MinLength: 1
    MaxLength: 30
  RDSPassword:
    AllowedPattern: ^[a-zA-Z0-9]+$
    ConstraintDescription: Must be between 8 to 30 alphanumeric characters.
    Type: String
    Description: The password to be used in the RDS connection.
    MinLength: 8
    MaxLength: 30

Resources:
  AWSAppSyncRDSGraphQLApi:
    Type: "AWS::AppSync::GraphQLApi"
    Properties:
      Name: !Sub ${projectName}_GraphQLApi
      AuthenticationType: API_KEY

  ApiKey:
    Type: "AWS::AppSync::ApiKey"
    Properties:
      ApiId: !GetAtt AWSAppSyncRDSGraphQLApi.ApiId
      Description: The Api Key for the AppSync Api
  AWSAppSyncRDSSecret:
    Type: "AWS::SecretsManager::Secret"
    Properties:
      Description: Generates a new secret for DB Cluster
      Name: !Sub ${projectName}_Secret
      SecretString: !Sub '{"username":"${RDSUsername}","password":"${RDSPassword}"}'
  AWSAppSyncRDSCluster:
    Type: "AWS::RDS::DBCluster"
    Properties:
      MasterUsername: !Sub ${RDSUsername}
      MasterUserPassword: !Sub ${RDSPassword}
      DatabaseName: !Sub ${projectName}_Database #Must match name in sql schema #Must match name in sql schema
      Engine: aurora
      EngineMode: serverless
      DBClusterIdentifier: !Sub ${projectName}-cluster
      EnableHttpEndpoint: true
      SourceRegion: !Sub "${AWS::Region}"

  AWSAppSyncRDSDBClusterParameterGroup:
    Type: "AWS::RDS::DBClusterParameterGroup"
    Properties:
      Description: CloudFormation Aurora Cluster Parameter Group
      Family: aurora-mysql5.7
      Parameters:
        time_zone: US/Eastern
        character_set_database: utf32
  AWSAppSyncRDSAttachSecret:
    Type: "AWS::SecretsManager::SecretTargetAttachment"
    Properties:
      SecretId: !Ref AWSAppSyncRDSSecret
      TargetId: !Ref AWSAppSyncRDSCluster
      TargetType: "AWS::RDS::DBCluster"
  AWSAppSyncRDSServiceRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: !Sub ${projectName}_Role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: appsync.amazonaws.com
            Action:
              - "sts:AssumeRole"
  AWSAppSyncRDSPolicy:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: !Sub ${projectName}_Policy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - "rds-data:*"
            Resource:
              - !Sub "arn:${AWS::Partition}:rds:${AWS::Region}:${AWS::AccountId}:cluster:${AWSAppSyncRDSCluster}"
              - !Sub "arn:${AWS::Partition}:rds:${AWS::Region}:${AWS::AccountId}:cluster:${AWSAppSyncRDSCluster}:*"
          - Effect: Allow
            Action:
              - "secretsmanager:GetSecretValue"
            Resource:
              - !Ref AWSAppSyncRDSSecret
              - !Sub "${AWSAppSyncRDSSecret}:*"
      Roles:
        - !Ref AWSAppSyncRDSServiceRole
  AWSAppSyncRDSDataSource:
    Type: "AWS::AppSync::DataSource"
    DependsOn:
      - AWSAppSyncRDSGraphQLApi
    Properties:
      ApiId: !GetAtt AWSAppSyncRDSGraphQLApi.ApiId
      Name: !Sub ${projectName}_DataSource
      Type: RELATIONAL_DATABASE
      ServiceRoleArn: !GetAtt AWSAppSyncRDSServiceRole.Arn
      RelationalDatabaseConfig:
        RelationalDatabaseSourceType: RDS_HTTP_ENDPOINT
        RdsHttpEndpointConfig:
          AwsRegion: !Sub "${AWS::Region}"
          AwsSecretStoreArn: !Ref AWSAppSyncRDSSecret
          DatabaseName: !Sub ${projectName}_Database #Must begin with a letter and contain only alphanumeric characters
          DbClusterIdentifier: !Sub "arn:${AWS::Partition}:rds:${AWS::Region}:${AWS::AccountId}:cluster:${AWSAppSyncRDSCluster}"
  GraphQLSchema:
    Type: "AWS::AppSync::GraphQLSchema"
    Properties:
      ApiId: !GetAtt AWSAppSyncRDSGraphQLApi.ApiId
      DefinitionS3Location: ./schema.graphql
  QueryTemplateReference:
    DependsOn: GraphQLSchema
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: ./Resolvers/Queries/queries.yml
      Parameters:
        ApiId: !GetAtt AWSAppSyncRDSGraphQLApi.ApiId
        DataSourceName: !GetAtt AWSAppSyncRDSDataSource.Name
        DatabaseName: !Sub ${projectName}_Database
        Environment: !Sub ${projectName}
        SecretArn: !Ref AWSAppSyncRDSSecret
        ClusterName: !Ref AWSAppSyncRDSCluster
  MutationTemplateReference:
    DependsOn: GraphQLSchema
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: ./Resolvers/Mutations/mutations.yml
      Parameters:
        Environment: !Sub ${projectName}
        DatabaseName: !Sub ${projectName}_Database
        SecretArn: !Ref AWSAppSyncRDSSecret
        ClusterName: !Ref AWSAppSyncRDSCluster
        ApiId: !GetAtt AWSAppSyncRDSGraphQLApi.ApiId
        DataSourceName: !GetAtt AWSAppSyncRDSDataSource.Name

Outputs:
  ApiUrl:
    Description: The GraphQL endpoint
    Value: !GetAtt AWSAppSyncRDSGraphQLApi.GraphQLUrl
  ApiKey:
    Description: The API key
    Value: !GetAtt ApiKey.ApiKey
  DatabaseName:
    Description: The database name
    Value: !Sub ${projectName}_Database #Must match name in sql schema
